(deftheme galileo-seamen
  "Created 2020-07-17.")

(custom-theme-set-faces
 'galileo-seamen
 '(default ((t (:inherit nil :stipple nil :background "#264653" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "ADBO" :family "Source Code Pro"))))
 '(cursor ((t (:background "#EAA3A6"))))
 '(fixed-pitch ((t (:foreground "#fffffff" :family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#8b1030"))))
 '(homoglyph ((((class color) (min-colors 89)) (:foreground "#8b1030"))))
 '(minibuffer-prompt ((t (:foreground "#ffffff"))))
 '(highlight ((((class color) (min-colors 89)) (:inherit (modus-theme-subtle-blue)))))
 '(region ((t (:background "#ffffff" :foreground "#264653"))))
 '(shadow ((t (:foreground "#8282B0"))))
 '(secondary-selection ((t (:background "#13242A" :foreground "#ffffff"))))
 '(trailing-whitespace ((t (:background "#EAA3A6"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:weight normal :foreground "#8f0075"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8282B0" :slant normal))))
 '(font-lock-comment-face ((t (:foreground "#8282B0" :slant normal))))
 '(font-lock-constant-face ((t (:foreground "#2A9D8F"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:slant normal :foreground "#093060"))))
 '(font-lock-function-name-face ((t (:foreground "#E9C46A" :slant italic))))
 '(font-lock-keyword-face ((t (:foreground "#F4A261" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:weight normal :foreground "#813e00"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#721045"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8BB689" :weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :foreground "#8b1030"))))
 '(font-lock-string-face ((t (:foreground "#8BB689"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#8f0075"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#00538b"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#703700"))))
 '(button ((t (:foreground "#07beb8" :underline t))))
 '(link ((t (:foreground "#07beb8" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:underline (:color foreground-color :style line) :foreground "#5317ac"))))
 '(fringe ((t (:background "#264653" :foreground "#ffffff"))))
 '(header-line ((t (:background "#264653" :foreground "#ffffff"))))
 '(mode-line ((t (:box (:line-width 1 :color "#1A1A28" :style nil) :foreground "#ffffff" :background "#193038"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#F4A261" :weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:box (:line-width -1 :color nil :style pressed-button) :inherit (modus-theme-active-blue)))))
 '(mode-line-inactive ((t (:background "#193038" :foreground "#ffffff" :box (:line-width 1 :color "#e0e0e0" :style nil)))))
 '(isearch ((((class color) (min-colors 89)) (:weight bold :inherit (modus-theme-intense-green)))))
 '(isearch-fail ((t (:inherit (modus-theme-refine-red) :background "#E76F51" :foreground "black"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:inherit (modus-theme-refine-cyan)))))
 '(match ((t (:inherit (modus-theme-special-calm) :background "#2A9D8F" :foreground "black" :underline (:color foreground-color :style line)))))
 '(next-error ((t (:inherit (modus-theme-subtle-red) :background "#2A9D8F"))))
 '(query-replace ((((class color) (min-colors 89)) (:weight bold :inherit (modus-theme-intense-yellow)))))
 '(org-level-1 ((t (:foreground "#ECCE83" :height 1.0))))
 '(line-number ((t (:background "#1c333d" :foreground "#ffffff"))))
 '(org-level-2 ((t (:weight bold :overline nil :foreground "#E76F51" :inherit default))))
 '(org-level-3 ((t (:weight bold :overline nil :foreground "#57ACB2" :inherit default))))
 '(org-level-4 ((t (:inherit default :foreground "#EAA3A6" :overline nil :weight bold))))
 '(org-level-5 ((t (:weight bold :overline nil :foreground "#ECCE83" :inherit default))))
 '(org-level-6 ((t (:weight bold :overline nil :foreground "#E76F51" :inherit default))))
 '(org-level-7 ((t (:weight bold :overline nil :foreground "#57ACB2" :inherit default))))
 '(org-level-8 ((t (:inherit default :foreground "#EAA3A6" :overline nil :weight bold))))
 '(org-block ((t (:foreground "#ffffff" :background "#274653" :inherit (fixed-pitch)))))
 '(org-block-begin-line ((t (:inherit (fixed-pitch) :background "#3f7184" :foreground "#ffffff"))))
 '(org-code ((t (:inherit fixed-pitch :foreground "#8BB689"))))
 '(org-document-info ((t (:foreground "#F4A261"))))
 '(org-document-title ((t (:height 1.2 :weight extra-bold :foreground "#F4A261" :inherit (default)))))
 '(org-document-info-keyword ((t (:foreground "#8282B0" :inherit (fixed-pitch)))))
 '(org-agenda-calendar-event ((t (:foreground "#ffffff"))))
 '(org-agenda-date ((t (:inherit default :foreground "#ECCE83" :overline nil))))
 '(org-agenda-date-weekend ((t (:inherit default :foreground "#E76F51" :overline nil))))
 '(org-agenda-structure ((t (:inherit default :foreground "#ffffff"))))
 '(org-checkbox-statistics-todo ((t (:foreground "#ffffff" :overline nil)))))

(provide-theme 'galileo-seamen)
