FROM ubuntu:latest
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y build-essential g++ libboost-all-dev
RUN g++ -std=c++20 <src.cpp> -o <exe>
EXPOSE 9003/udp
CMD ["./exe"]
