#!/bin/sh

if [ $# -ne 2 ] ; then
    echo "Usage: `basename $0` <orig.suffix> <new.suffix>"
    exit 1
fi

OLD=$1
NEW=$2

set $(find . -type f -name \*"$OLD")

for file in $*  ; do
    str="s/$OLD\$/$NEW/"
    name=$(echo "$file" | sed "$str")
    cp "$file" "$name"
done
