#!/bin/sh
# -*- Mode: sh -*-
# ec --- launch emacs client
# Copyright (C) 2021  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Wednesday, March 10, 2021
# Version: 1.0
# Modified Time-stamp: <2021-03-28 12:04:23 dharms>
# Modified by: Dan Harms
# Keywords: emacs tools

srv=${ESRV:-$(hostname -s)}
exec "$EMACS_CLIENT" -q -a "" -s $srv -n -c "$@"

# code ends here
