#!/bin/sh
# -*- Mode: sh -*-
# ec --- launch emacs client
# Copyright (C) 2021, 2023  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Wednesday, March 10, 2021
# Version: 1.0
# Modified Time-stamp: <2023-09-07 15:11:01 dharms>
# Modified by: Dan Harms
# Keywords: emacs tools

srv=${ESRV:-$(hostname -s)}
exec "$EMACS_CLIENT" -q -s $srv -n -r "$@"

# code ends here
