#!/bin/sh
# -*- Mode: sh -*-
# ec --- launch emacs client
# Copyright (C) 2021  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Wednesday, March 10, 2021
# Version: 1.0
# Modified Time-stamp: <2021-03-18 12:34:18 dharms>
# Modified by: Dan Harms
# Keywords: emacs tools

exec "$EMACS_CLIENT" -q -a "" -n -c "$@"

# code ends here
