#!/usr/bin/env sh
# -*- Mode: sh -*-
# ek --- kill emacs daemon
# Copyright (C) 2018-2019  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Thursday, August  9, 2018
# Version: 1.0
# Modified Time-stamp: <2019-02-28 12:07:45 dan.harms>
# Modified by: Dan Harms
# Keywords: emacs tools

server_ok()
{
    "$EMACS_ROOT"/bin/emacsclient -a "false" -e "(boundp 'server-process)"
}

if [ "t" = "$(server_ok)" ]; then
    echo "Shutting down Emacs server"
    "$EMACS_ROOT"/bin/emacsclient -e '(kill-emacs)'
else
    echo "Emacs server not running"
fi

# code ends here
