#!/usr/bin/env sh
# emacspipe --- pipe from stdin to emacs
# Copyright (C) 2015-2017  Dan Harms (dan.harms)
# Author: Dan Harms <dan.harms@xrtrading.com>
# Created: Thursday, September 24, 2015
# Version: 1.0
# Modified Time-stamp: <2017-12-20 09:13:17 dharms>
# Modified by: Dan Harms
# Keywords: emacs pipe stdin

exe=$VISUAL
# doesn't work: emacs: standard input is not a tty
# exe=$EDITOR
# or: emacsclient -c -n $@

# example: echo "hello world" | emacspipe -

# todo: explore the following alternative:
# echo "hello world" | sh -c '$EDITOR "$@" < /dev/tty' $EDITOR

if [[ $1 = - ]]; then
    temp=$(mktemp -t emacs-stdin-$USER.XXXXXXXX)
    cat - > $temp
    shift
    $exe $@ --eval "(progn (find-file \"$temp\")\
                       (set-visited-file-name nil)\
                       (rename-buffer \"*stdin*\" t))"
    # 2>&1 > /dev/null
else
    $($exe "$@")
fi

# emacspipe ends here
