#!/usr/bin/env sh
# emacspipe --- pipe from stdin to emacs
# Copyright (C) 2015, 2016  Dan Harms (dan.harms)
# Author: Dan Harms <dan.harms@xrtrading.com>
# Created: Thursday, September 24, 2015
# Version: 1.0
# Modified Time-stamp: <2016-09-01 13:23:31 dan.harms>
# Modified by: Dan Harms
# Keywords: emacs pipe stdin

exe=$EMACSX
# doesn't work: emacs: standard input is not a tty
# exe=$EDITOR
# or: emacsclient -c -n $@

# example: echo "hello world" | emacspipe -

if [ $1 = - ]; then
    temp=$(mktemp emacs-stdin-$USER.XXXXXXXX --tmpdir)
    cat - > $temp
    shift
    $exe $@ --eval "(progn (find-file \"$temp\")\
                       (set-visited-file-name nil)\
                       (rename-buffer \"*stdin*\" t))"
    # 2>&1 > /dev/null
else
    $($exe "$@")
fi

# emacspipe ends here
