#!/bin/sh
# -*- Mode: sh -*-
# emax --- open emacs client in gui frame
# Copyright (C) 2018-2021  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Tuesday, July 31, 2018
# Version: 1.0
# Modified Time-stamp: <2021-03-10 22:12:47 dharms>
# Modified by: Dan Harms
# Keywords: emacs tools

visible_frames()
{
    "$EMACS_CLIENT" -a "" -e '(length (visible-frame-list))'
}

change_focus()
{
    "$EMACS_CLIENT" -n -e "(select-frame-set-input-focus (selected-frame))" > /dev/null 2>&1
}

test "$(visible_frames)" -eq "1" && change_focus

if [ "$(visible_frames)" -lt "2" ]; then
    # need to create a frame
    "$EMACS_CLIENT" -n -c "$@" && change_focus
else
    # already a visible frame besides daemon
    change_focus
    # -n $@ errors when no args
    test "$#" -ne "0" && "$EMACS_CLIENT" -n "$@"
fi

# code ends here
