#!/bin/sh
# -*- Mode: sh -*-
# ex --- launch emacs client + server if needed
# Copyright (C) 2021, 2023  Dan Harms (dharms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Wednesday, March 10, 2021
# Version: 1.0
# Modified Time-stamp: <2023-09-25 10:33:10 dharms>
# Modified by: Dan Harms
# Keywords: emacs tools

srv=${ESRV:-$(hostname -s)}
exec "$EMACS_CLIENT" -q -a "" -s "$srv" -n -r "$@"

# code ends here
