#!/bin/sh
# -*- Mode: sh -*-
# pdb --- a pdb wrapper
# Copyright (C) 2019-2020  Dan Harms (dan.harms)
# Author: Dan Harms <enniomore@icloud.com>
# Created: Tuesday, October 15, 2019
# Version: 1.0
# Modified Time-stamp: <2020-09-23 12:27:26 dharms>
# Modified by: Dan Harms
# Keywords: tools python debugging

exec python -m pdb "$@"

# code ends here
