#!/bin/sh

if [ $# -ne 1 ] ; then
    echo "Usage: `basename $0` <orig.suffix>"
    exit 1
fi

EXT=$1

set $(find . -type f -name \*"$EXT")

for file in $*  ; do
    str="s/$EXT\$//"
    name=$(echo "$file" | sed "$str")
    cp "$file" "$name"
done
