;;; nibelung-theme-base.el --- Base theme generator -*- lexical-binding: t; -*-

(defun nibelung-theme-create (theme-name palette)
  "Create a theme with THEME-NAME using colors from PALETTE."
  (let* ((bg                  (plist-get palette :bg))
         (fg                  (plist-get palette :fg))
         (level0              (plist-get palette :level0))
         (level1              (plist-get palette :level1))
         (level2              (plist-get palette :level2))
         (level3              (plist-get palette :level3))
         (level4              (plist-get palette :level4))
         (level5              (plist-get palette :level5))
         (level6              (plist-get palette :level6))
         (_accent-subtle      (plist-get palette :accent-subtle))
         (accent-light        (plist-get palette :accent-light))
         (_accent-bright      (plist-get palette :accent-bright))
         (_accent-match       (plist-get palette :accent-match))
         (emphasis            (plist-get palette :emphasis))
         (link-color          (plist-get palette :link))
         (comment-bg          (plist-get palette :comment-bg))
         (rainbow-blue        (plist-get palette :rainbow-blue))
         (rainbow-red         (plist-get palette :rainbow-red))
         (rainbow-orange      (plist-get palette :rainbow-orange))
         (rainbow-yellow      (plist-get palette :rainbow-yellow))
         (rainbow-green       (plist-get palette :rainbow-green))
         (rainbow-cyan        (plist-get palette :rainbow-cyan))
         (rainbow-bluelight   (plist-get palette :rainbow-bluelight))
         (rainbow-magenta     (plist-get palette :rainbow-magenta))

         ;; FACES definitions
         (bold `((t (:inherit default :foreground ,emphasis :weight normal))))
         (builtin `((t (:inherit default :foreground ,level3 :weight normal))))
         (code-block `((t (:inherit default :extend t :weight normal))))
         (code-block-header `((t (:inherit default :extend t :foreground ,level2 :weight normal))))
         (comment `((t (:inherit default :extend t :background ,comment-bg :foreground ,level3 :weight normal))))
         (constant `((t (:inherit default :foreground ,level4 :weight normal))))
         (cursor `((t (:foreground ,bg))))
         (default `((t (:foreground ,fg :background ,bg :weight normal))))
         (function `((t (:inherit default :foreground ,level5 :weight normal))))
         (header `((t (:inherit default :background ,level4 :foreground ,level0 :weight normal :height 1.0))))
         (_header-not-extended `((t (:inherit default :extend nil :background ,level4 :foreground ,level0 :weight normal))))
         (highlight `((t (:inherit default :override t :background ,level4 :foreground ,level0 :distant-foreground ,level0 :weight normal))))
         (link `((t (:inherit default :foreground ,link-color :underline t :weight normal))))
         (lpadding '(:box (:line-width (10 . 1) :style flat-button)))
         (match `((t (:inherit default :background ,emphasis :foreground ,level1 :weight normal))))
         (modeline `((t (:inherit default :background ,fg :foreground ,level0 :weight normal :height 1.0))))
         (modeline-indicator header)
         (modeline-white `((t (:inherit default :foreground ,level5 :background ,level0 :weight normal :height 1.0))))
         (optional `((t (:inherit default :foreground ,level2 :weight normal))))
         (org-done `((t (:background ,bg :foreground ,fg :height 0.95 :weight normal ,@lpadding))))
         (org-todo* `((t (:background ,fg :foreground ,bg :height 0.95 :weight normal ,@lpadding))))
         (replace-confirm `((t (:inherit default :background ,level4 :foreground ,level0 :weight normal))))
         (replace-match* `((t (:inherit default :background ,level5 :foreground ,level0 :weight normal))))
         (string* optional)
         (symbol `((t (:inherit default :foreground ,level5 :weight normal))))
         (text `((t (:inherit default :foreground ,fg :weight normal))))
         (type builtin)
         (variable constant))

    (custom-theme-set-faces
     theme-name
     `(default ,default)
     `(cursor ,cursor)
     `(highlight ,highlight)
     `(hl-line ((t (:inherit default :background ,level0 :weight normal))))
     `(header-line ((t (:inherit default :background ,level0))))
     `(tab-bar ((t (:inherit default :background ,level0))))
     `(tab-bar-tab ((t (:inherit default :background ,bg :foreground ,fg))))
     `(tab-bar-tab-inactive ((t (:inherit default :background ,level0 :foreground ,level3))))
     `(tab-line ((t (:inherit default :background ,level0))))
     `(tab-line-tab ((t (:inherit default :background ,bg :foreground ,fg))))
     `(tab-line-tab-current ((t (:inherit default :background ,bg :foreground ,fg))))
     `(tab-line-tab-inactive ((t (:inherit default :background ,level0 :foreground ,level3))))
     `(bold ((t (:inherit default :foreground ,emphasis :weight normal))))
     `(bold-italic ((t (:inherit default :foreground ,emphasis :weight normal))))
     `(italic ((t (:foreground ,emphasis))))
     `(fringe ((t (:inherit default :background ,bg))))
     `(line-number-current-line ((t (:inherit default :background ,bg :foreground ,emphasis))))
     `(fill-column-indicator ((t (:foreground ,level1))))
     `(child-frame-border ((t (:background ,level2))))
     `(internal-border ((t (:background ,level0))))
     `(escape-glyph ((t (:foreground ,level4))))
     `(file-name-shadow ,optional)
     `(button ,link)
     `(link-visited ((t (:foreground ,level4 :underline t))))
     ;; Constant
     `(font-lock-builtin-face ,builtin)
     `(font-lock-preprocessor-face ,type)
     `(font-lock-constant-face ,constant)
     `(font-lock-function-call-face ,bold)
     `(highlight-quoted-symbol ,symbol)
     `(font-lock-keyword-face ,constant)
     `(clojure-keyword-face ,builtin)
     `(clojure-character-face ,constant)
     `(font-lock-string-face ,string*)
     `(font-lock-delimiter-face ((t (:inherit default :foreground ,emphasis :weight normal))))
     `(font-lock-type-face ,type)
     `(font-lock-function-name-face ,optional)
     `(font-lock-variable-name-face ,builtin)
     `(font-lock-bracket-face ,optional)
     `(tree-sitter-hl-face:string ,constant)
     `(tree-sitter-hl-face:string.delimiter ,constant)
     `(tree-sitter-hl-face:property ,optional)
     `(tree-sitter-hl-face:keyword ,optional)
     `(tree-sitter-hl-face:punctuation ,optional)
     `(tree-sitter-hl-face:punctuation.delimiter ,optional)
     `(treesit-fold-replacement-face ,optional)
     `(font-lock-escape-face ,optional)
     `(font-lock-operator-face ,optional)
     `(font-lock-number-face ,constant)
     `(font-lock-property-name-face ,optional)
     `(font-lock-property-use-face ,optional)
     `(font-lock-variable-use-face ,builtin)
     `(font-lock-punctuation-face ,optional)
     `(font-lock-misc-punctuation-face ,optional)
     `(font-lock-regexp-face ,constant)
     `(font-lock-negation-char-face ,constant)
     `(font-lock-doc-markup-face ,optional)
     ;; Comment
     `(font-lock-comment-delimiter-face ,comment)
     `(font-lock-comment-face ,comment)
     `(font-lock-doc-face ,optional)
     `(font-lock-warning-face ((t (:inherit default :foreground ,fg))))
     ;; Misc
     `(shadow ,optional)
     `(whitespace-tab ,optional)
     `(sh-quoted-exec ,optional)
     `(line-number ((t (:inherit default :background ,bg :foreground ,fg))))
     `(message-header-newsgroups ,text)
     `(message-header-xheader ,text)
     `(message-header-cc ,text)
     `(message-header-to ,text)
     `(minibuffer-prompt ,code-block-header)
     `(marginalia-documentation ,optional)
     `(custom-set ,text)
     `(icon ,optional)
     `(+fold-hideshow-folded-face ,optional)
     `(read-multiple-choice-face ,text)
     `(helpful-heading ,comment)
     ;; Custom Menu
     `(custom-variable-tag ,variable)
     `(custom-variable-documentation ,optional)
     `(custom-documentation ,optional)
     `(custom-state ,bold)
     `(custom-visibility ,bold)
     `(custom-group-tag ,header)
     `(custom-button-unraised ,constant)
     `(custom-button ,function)
     `(custom-button-mouse ,header)
     `(widget-field ,symbol)
     `(widget-unselected ,optional)
     ;; Company
     `(company-tooltip ,function)
     `(company-tooltip-common ,match)
     `(company-tooltip-selection ,match)
     `(company-tooltip-scrollbar-thumb ,header)
     `(company-tooltip-scrollbar-track ,variable)
     `(company-echo-common ,variable)
     `(company-tooltip-annotation ,variable)
     ;; Match
     `(evil-ex-lazy-highlight ,match)
     `(match ,match)
     `(region ,match)
     `(bold ,bold)
     `(orderless-match-face-0 ,match)
     `(orderless-match-face-1 ,match)
     `(show-paren-match ,match)
     `(isearch ,replace-match*)
     `(isearch-fail ((t (:inherit default :background ,level5 :foreground ,level0))))
     `(isearch-group-1 ,replace-confirm)
     `(isearch-group-2 ,match)
     `(lazy-highlight ,replace-match*)
     `(evil-ex-substitute-replacement ,replace-confirm)
     `(orderless-match-face-2 ,bold)
     `(orderless-match-face-3 ,bold)
     ;; Warnings
     `(success ,optional)
     `(warning ,header)
     `(error ,replace-match*)
     `(flymake-error ((t (:inherit default :extend t :background ,level5 :foreground ,level0))))
     `(flymake-warning ((t (:inherit default :underline (:color ,level4 :style line :position t)))))
     `(flymake-note ((t (:inherit default :underline (:color ,emphasis :style line :position t)))))
     `(flymake-error-echo ((t (:foreground ,level5))))
     `(flymake-warning-echo ((t (:foreground ,level4))))
     `(flymake-note-echo ((t (:foreground ,emphasis))))
     `(flymake-popon ((t (:background ,level0 :foreground ,fg))))
     ;; Modeline
     `(doom-nano-modeline-evil-insert-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-motion-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-visual-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-emacs-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-operator-state-face ,modeline-indicator)
     `(doom-nano-modeline-evil-normal-state-face ,modeline-indicator)
     `(doom-nano-modeline-inactive ,modeline-white)
     `(doom-nano-modeline-cursor-position-face ,modeline)
     `(doom-nano-modeline-evil-replace-state-face ,modeline-indicator)
     `(doom-nano-modeline-active-face ,modeline)
     `(doom-nano-modeline-inactive-face ,modeline-white)
     `(doom-nano-modeline-macro-face ,modeline-indicator)
     `(doom-nano-modeline-major-mode-face ,modeline)
     `(doom-nano-modeline-org-clock-face ,modeline)
     `(doom-nano-modeline-visual-selection-information-face ,modeline)
     `(doom-nano-modeline-vc-branch-name-face ,modeline-indicator)
     `(mode-line ,modeline)
     `(mode-line-buffer-id ,modeline)
     `(mode-line-emphasis ,modeline)
     `(mode-line-highlight ,modeline)
     `(mode-line-faces ,modeline)
     `(mode-line-inactive ,modeline-white)
     `(doom-dashboard-loaded ,builtin)
     `(+workspace-tab-face ((t (:inherit default :background ,level0 :foreground ,level3))))
     `(+workspace-tab-selected-face ((t (:inherit default :background ,bg :foreground ,fg))))
     ;; Links
     `(diary ,link)
     `(link ,link)
     ;; Org Mode
     `(+org-todo-active ,org-todo*)
     `(+org-todo-cancel ,code-block-header)
     `(+org-todo-onhold ,org-done)
     `(+org-todo-project ,org-todo*)
     `(org-hide ((t (:inherit default :foreground ,bg))))
     `(org-agenda-date ,text)
     `(org-agenda-date-today ,code-block-header)
     `(org-agenda-date-weekend ,text)
     `(org-agenda-done ,optional)
     `(org-agenda-structure ,text)
     `(org-block ,code-block)
     `(org-quote ,code-block)
     `(org-block-begin-line ,code-block-header)
     `(org-block-end-line ,code-block-header)
     `(org-done ,optional)
     `(org-document-title ,constant)
     `(org-ellipsis ,optional)
     `(org-headline-done ,optional)
     `(org-list-dt ,constant)
     `(org-meta-line ,constant)
     `(org-modern-done ,org-done)
     `(org-modern-block-name ,constant)
     `(org-modern-label ,org-todo*)
     `(org-modern-todo ,org-todo*)
     `(org-modern-tag ,org-done)
     `(org-modern-date-active ,org-todo*)
     `(org-modern-date-inactive ,org-done)
     `(org-modern-time-active ,org-todo*)
     `(org-modern-time-inactive ,org-done)
     `(org-modern-progress-complete ,org-done)
     `(org-modern-progress-incomplete ,org-todo*)
     `(org-modern-priority ((t (:inherit default :background ,level3
                                :foreground ,fg
                                :box (:line-width (2 . 1)
                                      :color ,bg
                                      :style flat-button)))))
     `(org-formula ,match)
     `(org-document-info ,symbol)
     `(org-todo ,org-todo*)
     `(org-tag ,function)
     `(org-date ,link)
     `(org-drawer ,optional)
     `(org-checkbox ,optional)
     `(org-list-dt ,optional)
     `(outline-3 ,constant)
     `(outline-2 ,symbol)
     `(outline-1 ,function)
     `(outline-4 ,bold)
     `(markdown-header-face-3 ((t (:foreground ,level4))))
     `(markdown-header-face-2 ((t (:foreground ,level5))))
     `(markdown-header-face-1 ((t (:foreground ,level6))))
     `(markdown-header-face-4 ((t (:foreground ,rainbow-blue))))
     `(org-table ,constant)
     ;; Dired
     `(dired-broken-symlink ((t (:foreground ,level5))))
     `(dired-directory ,constant)
     `(dired-flagged ((t (:foreground ,level5))))
     `(dired-header ,code-block-header)
     `(dired-ignored ,optional)
     `(dired-mark ,bold)
     `(dired-marked ,bold)
     `(dired-perm-write ,optional)
     `(dired-set-id ,constant)
     `(dired-special ,constant)
     `(dired-symlink ,link)
     `(dired-warning ((t (:foreground ,level4))))
     ;; Diredfl
     `(diredfl-autofile-name ,text)
     `(diredfl-compressed-file-name ,text)
     `(diredfl-compressed-file-suffix ,constant)
     `(diredfl-date-time ,optional)
     `(diredfl-deletion ((t (:foreground ,level5))))
     `(diredfl-deletion-file-name ((t (:foreground ,level5))))
     `(diredfl-dir-heading ,code-block-header)
     `(diredfl-dir-name ,constant)
     `(diredfl-dir-priv ,builtin)
     `(diredfl-exec-priv ,constant)
     `(diredfl-executable-tag ,bold)
     `(diredfl-file-name ,text)
     `(diredfl-file-suffix ,optional)
     `(diredfl-flag-mark ,bold)
     `(diredfl-flag-mark-line ((t (:inherit default :extend t))))
     `(diredfl-ignored-file-name ,optional)
     `(diredfl-link-priv ,constant)
     `(diredfl-no-priv ,optional)
     `(diredfl-number ,optional)
     `(diredfl-other-priv ,optional)
     `(diredfl-rare-priv ,constant)
     `(diredfl-read-priv ,optional)
     `(diredfl-symlink ,link)
     `(diredfl-tagged-autofile-name ,optional)
     `(diredfl-write-priv ,optional)
     `(dgi-commit-message-face ,optional)
     ;; Dirvish
     `(dirvish-file-device-number ,optional)
     `(dirvish-file-group-id ,optional)
     `(dirvish-file-inode-number ,optional)
     `(dirvish-file-link-number ,optional)
     `(dirvish-file-modes ,optional)
     `(dirvish-file-size ,optional)
     `(dirvish-file-time ,optional)
     `(dirvish-file-user-id ,optional)
     `(dirvish-free-space ,optional)
     `(dirvish-git-commit-message-face ,optional)
     `(dirvish-hl-line ((t (:inherit default))))
     `(dirvish-hl-line-inactive ((t (:inherit default :foreground ,level2))))
     `(dirvish-inactive ,optional)
     `(dirvish-media-info-heading ,code-block-header)
     `(dirvish-media-info-property-key ,constant)
     `(dirvish-proc-failed ((t (:foreground ,level5))))
     `(dirvish-proc-finished ,optional)
     `(dirvish-proc-running ,bold)
     `(dirvish-subtree-guide ,optional)
     `(dirvish-subtree-state ,optional)
     `(dirvish-vc-added-state ((t (:foreground ,rainbow-green))))
     `(dirvish-vc-conflict-state ((t (:foreground ,rainbow-red))))
     `(dirvish-vc-edited-state ((t (:foreground ,level4))))
     `(dirvish-vc-locked-state ((t (:foreground ,level3))))
     `(dirvish-vc-missing-state ((t (:foreground ,level5))))
     `(dirvish-vc-needs-merge-face ((t (:foreground ,level4))))
     `(dirvish-vc-needs-update-state ((t (:foreground ,level4))))
     `(dirvish-vc-removed-state ((t (:foreground ,rainbow-red))))
     `(dirvish-vc-unregistered-face ((t (:foreground ,level3))))
     `(help-key-binding ,text)
     ;; Rainbow delimiters
     `(rainbow-delimiters-depth-4-face ((t (:foreground ,level4))))
     `(rainbow-delimiters-depth-3-face ((t (:foreground ,rainbow-blue))))
     `(rainbow-delimiters-depth-2-face ((t (:foreground ,level3))))
     `(rainbow-delimiters-depth-1-face ((t (:foreground ,accent-light))))
     `(rainbow-delimiters-unmatched-face ,header)
     `(rainbow-delimiters-base-error-face ,header)
     `(rainbow-delimiters-mismatched-face ,header)
     ;; Magit
     `(magit-tag ,header)
     `(magit-section-highlight ((t (:background ,bg :foreground ,fg))))
     `(magit-diff-context ((t (:foreground ,level3))))
     `(magit-diff-context-highlight ((t (:foreground ,fg))))
     `(magit-branch-local ,match)
     `(magit-branch-remote ,header)
     `(magit-branch-remote-head ,header)
     `(magit-branch-upstream ,optional)
     `(magit-branch-warning ((t (:foreground ,level5))))
     `(magit-section-heading ,code-block-header)
     `(magit-branch-current ,match)
     `(magit-hash ,optional)
     `(magit-dimmed ,optional)
     `(magit-filename ,text)
     `(magit-head ,match)
     `(magit-header-line ((t (:inherit default :background ,level0))))
     `(magit-header-line-key ,bold)
     `(magit-keyword ,constant)
     `(magit-reflog-commit ,comment)
     `(magit-reflog-amend ,comment)
     `(magit-reflog-checkout ,optional)
     `(magit-reflog-cherry-pick ,comment)
     `(magit-reflog-merge ,comment)
     `(magit-reflog-other ,optional)
     `(magit-reflog-rebase ,comment)
     `(magit-reflog-remote ,optional)
     `(magit-reflog-reset ((t (:foreground ,level5))))
     `(magit-process-ok ((t (:foreground ,rainbow-green))))
     `(magit-process-ng ((t (:foreground ,rainbow-red))))
     `(magit-mode-line-process ((t (:foreground ,emphasis))))
     `(magit-mode-line-process-error ((t (:foreground ,level5))))
     `(magit-diff-added ((t (:foreground ,rainbow-green))))
     `(magit-diff-added-highlight ((t (:foreground ,rainbow-green))))
     `(magit-diff-removed ((t (:foreground ,rainbow-red))))
     `(magit-diff-removed-highlight ((t (:foreground ,rainbow-red))))
     `(magit-diff-base ((t (:foreground ,rainbow-yellow))))
     `(magit-diff-base-highlight ((t (:foreground ,rainbow-yellow))))
     `(diff-refine-added ((t (:background ,level1 :foreground ,rainbow-green))))
     `(diff-refine-removed ((t (:background ,level1 :foreground ,rainbow-red))))
     `(diff-refine-changed ((t (:background ,level1 :foreground ,rainbow-yellow))))
     `(magit-diff-lines-heading ,match)
     `(magit-section-heading ,variable)
     `(magit-diff-hunk-heading ((t (:background ,level1 :foreground ,fg))))
     `(magit-diff-hunk-heading-highlight ((t (:background ,level1 :foreground ,fg))))
     `(magit-diff-file-heading ,symbol)
     `(magit-diff-file-heading-highlight ((t (:background ,level0))))
     `(magit-diff-whitespace-warning ((t (:background ,level5))))
     `(magit-diffstat-added ((t (:foreground ,rainbow-green))))
     `(magit-diffstat-removed ((t (:foreground ,rainbow-red))))
     `(magit-log-author ,optional)
     `(magit-log-date ,optional)
     `(magit-log-graph ,optional)
     ;; Magit blame
     `(magit-blame-heading ((t (:background ,level0 :foreground ,fg))))
     `(magit-blame-highlight ((t (:background ,level0))))
     `(magit-blame-hash ,optional)
     `(magit-blame-name ,text)
     `(magit-blame-date ,optional)
     `(magit-blame-summary ,text)
     `(magit-blame-dimmed ,optional)
     `(magit-blame-margin ,optional)
     ;; Transient
     `(transient-key-stay ,text)
     `(transient-key-exit ,constant)
     `(transient-heading ,code-block-header)
     `(transient-value ,match)
     `(transient-argument ,match)
     `(transient-active-infix ,match)
     `(transient-delimiter ((t (:foreground ,level2))))
     `(transient-disabled-suffix ,optional)
     `(transient-enabled-suffix ,match)
     `(transient-higher-level ,bold)
     `(transient-inactive-argument ,optional)
     `(transient-inactive-value ,optional)
     `(transient-inapt-argument ,optional)
     `(transient-inapt-suffix ,optional)
     `(transient-key ,text)
     `(transient-key-noop ,optional)
     `(transient-key-recurse ,bold)
     `(transient-key-return ,bold)
     `(transient-key-stack ((t (:foreground ,emphasis))))
     `(transient-mismatched-key ((t (:foreground ,level5))))
     `(transient-nonstandard-key ((t (:foreground ,level4))))
     `(transient-unreachable ,optional)
     `(transient-unreachable-key ,optional)
     ;; Diff
     `(diff-added ((t (:foreground ,rainbow-green))))
     `(diff-removed ((t (:foreground ,rainbow-red))))
     `(diff-changed ((t (:foreground ,rainbow-yellow))))
     `(diff-header ((t (:background ,level0))))
     `(diff-file-header ((t (:background ,level0 :foreground ,fg))))
     `(diff-hunk-header ((t (:background ,level1 :foreground ,fg))))
     `(diff-context ((t (:foreground ,level3))))
     `(diff-indicator-added ((t (:foreground ,rainbow-green))))
     `(diff-indicator-removed ((t (:foreground ,rainbow-red))))
     `(diff-indicator-changed ((t (:foreground ,rainbow-yellow))))
     ;; Git Commit
     `(git-commit-summary ,text)
     `(git-commit-overlong-summary ((t (:foreground ,level5))))
     `(git-commit-keyword ,constant)
     `(git-commit-comment-heading ,code-block-header)
     `(git-commit-comment-branch-local ,match)
     `(git-commit-comment-branch-remote ,header)
     `(git-commit-comment-file ,text)
     `(git-commit-comment-action ,optional)
     ;; Treesitter
     `(ts-fold-replacement-face ,optional)
     ;; Cider
     `(cider-result-overlay-face ,modeline-indicator)
     `(cider-test-success-face ,match)
     `(cider-error-overlay-face ,replace-confirm)
     `(cider-test-failure-face ,replace-confirm)
     `(cider-instrumented-face ,link)
     `(cider-debug-code-overlay-face ,code-block)
     `(cider-debug-prompt-face ,code-block-header)
     `(cider-deprecated-face ((t (:foreground ,level4))))
     `(cider-docview-emphasis-face ((t (:foreground ,emphasis))))
     `(cider-docview-literal-face ,constant)
     `(cider-docview-strong-face ,bold)
     `(cider-docview-table-border-face ((t (:foreground ,level2))))
     `(cider-enlightened-face ,match)
     `(cider-enlightened-local-face ((t (:foreground ,emphasis))))
     `(cider-error-highlight-face ,header)
     `(cider-fragile-button-face ((t (:foreground ,level4))))
     `(cider-fringe-good-face ,match)
     `(cider-reader-conditional-face ((t (:foreground ,level4))))
     `(cider-repl-input-face ,bold)
     `(cider-repl-prompt-face ,code-block-header)
     `(cider-repl-result-face ((t (:foreground ,level4))))
     `(cider-repl-stderr-face ((t (:foreground ,level5))))
     `(cider-repl-stdout-face ((t (:foreground ,level3))))
     `(cider-stacktrace-error-class-face ,bold)
     `(cider-stacktrace-error-message-face ((t (:foreground ,level5))))
     `(cider-stacktrace-face ((t (:foreground ,level3))))
     `(cider-stacktrace-filter-active-face ,match)
     `(cider-stacktrace-filter-inactive-face ,optional)
     `(cider-stacktrace-fn-face ,function)
     `(cider-stacktrace-ns-face ,constant)
     `(cider-stacktrace-promoted-button-face ,bold)
     `(cider-stacktrace-suppressed-button-face ((t (:foreground ,level3))))
     `(cider-test-error-face ((t (:foreground ,level5))))
     `(cider-traced-face ((t (:foreground ,emphasis))))
     `(cider-warning-highlight-face ((t (:foreground ,level4))))
     `(cider-browse-ns-extra-info-face ((t (:foreground ,level3))))
     ;; Eshell
     `(eshell-syntax-highlighting-shell-command-face ,bold)
     `(eshell-prompt ,optional)
     `(eshell-syntax-highlighting-invalid-face ,match)
     ;; Colors
     `(ansi-color-black          ((t (:foreground ,level6))))
     `(ansi-color-blue           ((t (:foreground ,rainbow-blue))))
     `(ansi-color-bright-black   ((t (:foreground ,level5))))
     `(ansi-color-bright-blue    ((t (:foreground ,rainbow-cyan))))
     `(ansi-color-bright-cyan    ((t (:foreground ,rainbow-green))))
     `(ansi-color-bright-green   ((t (:foreground ,rainbow-green))))
     `(ansi-color-bright-magenta ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-bright-red     ((t (:foreground ,rainbow-red))))
     `(ansi-color-bright-white   ((t (:foreground ,rainbow-bluelight))))
     `(ansi-color-bright-yellow  ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-cyan           ((t (:foreground ,rainbow-cyan))))
     `(ansi-color-faint          ((t (:foreground ,rainbow-orange))))
     `(ansi-color-fast-blink     ((t (:foreground ,rainbow-blue))))
     `(ansi-color-green          ((t (:foreground ,rainbow-green))))
     `(ansi-color-inverse        ((t (:foreground ,rainbow-orange))))
     `(ansi-color-italic         ((t (:foreground ,rainbow-bluelight))))
     `(ansi-color-magenta        ((t (:foreground ,rainbow-magenta))))
     `(ansi-color-red            ((t (:foreground ,rainbow-red))))
     `(ansi-color-slow-blink     ((t (:foreground ,rainbow-magenta))))
     `(ansi-color-underline      ,link)
     `(ansi-color-white          ((t (:foreground ,rainbow-orange))))
     `(ansi-color-yellow         ((t (:foreground ,rainbow-yellow))))
     `(ansi-color-bold ,bold)

     ;; ========================================
     ;; EXPERIMENTAL FACES
     ;; ========================================
     ;; These faces are work in progress and may not be fully tested
     ;; Contributions and feedback welcome

     ;; Doom Modeline
     `(doom-modeline-bar ((t (:background ,emphasis))))
     `(doom-modeline-bar-inactive ((t (:background ,level2))))
     `(doom-modeline-buffer-file ((t (:foreground ,fg))))
     `(doom-modeline-buffer-path ((t (:foreground ,level4))))
     `(doom-modeline-buffer-modified ((t (:foreground ,emphasis))))
     `(doom-modeline-buffer-major-mode ((t (:foreground ,level4))))
     `(doom-modeline-project-dir ((t (:foreground ,level4))))
     `(doom-modeline-project-root-dir ((t (:foreground ,fg))))
     `(doom-modeline-info ((t (:foreground ,emphasis))))
     `(doom-modeline-warning ((t (:foreground ,level4))))
     `(doom-modeline-urgent ((t (:foreground ,level5))))
     `(doom-modeline-debug ((t (:foreground ,level5))))

     ;; LSP
     `(lsp-face-highlight-textual ((t (:background ,level1))))
     `(lsp-face-highlight-read ((t (:background ,level1 :underline t))))
     `(lsp-face-highlight-write ((t (:background ,level1))))
     `(lsp-ui-doc-background ((t (:background ,level0))))
     `(lsp-ui-doc-border ((t (:foreground ,level2))))
     `(lsp-ui-doc-header ((t (:background ,level1 :foreground ,fg))))
     `(lsp-ui-sideline-code-action ((t (:foreground ,emphasis))))
     `(lsp-ui-sideline-current-symbol ((t (:foreground ,emphasis))))
     `(lsp-ui-sideline-symbol ((t (:foreground ,level3))))

     ;; Eglot
     `(eglot-code-action-indicator-face ,bold)
     `(eglot-diagnostic-tag-deprecated-face ((t (:strike-through t))))
     `(eglot-diagnostic-tag-unnecessary-face ,optional)
     `(eglot-highlight-symbol-face ((t (:background ,level1))))
     `(eglot-inlay-hint-face ((t (:foreground ,level3))))
     `(eglot-mode-line ((t (:foreground ,level4))))
     `(eglot-parameter-hint-face ((t (:foreground ,level3))))
     `(eglot-type-hint-face ((t (:foreground ,level3))))
     ;; Eglot semantic tokens — types
     `(eglot-semantic-class ,builtin)
     `(eglot-semantic-enum ,builtin)
     `(eglot-semantic-interface ,builtin)
     `(eglot-semantic-namespace ,builtin)
     `(eglot-semantic-struct ,builtin)
     `(eglot-semantic-type ,builtin)
     `(eglot-semantic-typeParameter ,builtin)
     ;; Eglot semantic tokens — callables
     `(eglot-semantic-function ,bold)
     `(eglot-semantic-method ,bold)
     `(eglot-semantic-macro ,constant)
     `(eglot-semantic-decorator ,constant)
     ;; Eglot semantic tokens — values
     `(eglot-semantic-variable ,builtin)
     `(eglot-semantic-parameter ,optional)
     `(eglot-semantic-property ,optional)
     `(eglot-semantic-enumMember ,constant)
     `(eglot-semantic-event ,bold)
     ;; Eglot semantic tokens — literals/text
     `(eglot-semantic-number ,constant)
     `(eglot-semantic-string ,optional)
     `(eglot-semantic-regexp ,constant)
     `(eglot-semantic-keyword ,constant)
     `(eglot-semantic-operator ,optional)
     `(eglot-semantic-comment ,comment)
     `(eglot-semantic-documentation ,optional)
     ;; Eglot semantic tokens — modifiers (additive, minimal)
     `(eglot-semantic-abstract ((t nil)))
     `(eglot-semantic-async ((t nil)))
     `(eglot-semantic-declaration ((t nil)))
     `(eglot-semantic-defaultLibrary ((t nil)))
     `(eglot-semantic-definition ((t nil)))
     `(eglot-semantic-deprecated ((t (:strike-through t))))
     `(eglot-semantic-modification ((t nil)))
     `(eglot-semantic-modifier ((t nil)))
     `(eglot-semantic-readonly ((t nil)))
     `(eglot-semantic-static ((t nil)))

     ;; Flycheck
     `(flycheck-error ((t (:underline (:color ,level5 :style wave)))))
     `(flycheck-warning ((t (:underline (:color ,level4 :style wave)))))
     `(flycheck-info ((t (:underline (:color ,emphasis :style wave)))))
     `(flycheck-fringe-error ((t (:foreground ,level5))))
     `(flycheck-fringe-warning ((t (:foreground ,level4))))
     `(flycheck-fringe-info ((t (:foreground ,emphasis))))

     ;; Git Gutter
     `(git-gutter:added ((t (:foreground ,emphasis))))
     `(git-gutter:deleted ((t (:foreground ,level5))))
     `(git-gutter:modified ((t (:foreground ,level4))))
     `(git-gutter:unchanged ((t (:foreground ,level2))))
     `(git-gutter-fr:added ((t (:foreground ,emphasis))))
     `(git-gutter-fr:deleted ((t (:foreground ,level5))))
     `(git-gutter-fr:modified ((t (:foreground ,level4))))

     ;; Diff-HL
     `(diff-hl-change ((t (:foreground ,level4 :background ,level1))))
     `(diff-hl-delete ((t (:foreground ,level5 :background ,level1))))
     `(diff-hl-insert ((t (:foreground ,emphasis :background ,level1))))
     `(diff-hl-dired-change ((t (:foreground ,level4))))
     `(diff-hl-dired-delete ((t (:foreground ,level5))))
     `(diff-hl-dired-insert ((t (:foreground ,emphasis))))
     `(diff-hl-dired-unknown ((t (:foreground ,level3))))
     `(diff-hl-dired-ignored ((t (:foreground ,level2))))

     ;; Vertico
     `(vertico-current ((t (:foreground ,emphasis))))
     `(vertico-group-title ((t (:foreground ,level4))))
     `(vertico-group-separator ((t (:foreground ,level2))))
     `(vertico-multiline ,default)
     `(vertico-posframe ((t (:background ,level0))))
     `(vertico-posframe-border ((t (:background ,level2))))
     `(vertico-posframe-border-2 ((t (:background ,level2))))
     `(vertico-posframe-border-3 ((t (:background ,level2))))
     `(vertico-posframe-border-4 ((t (:background ,level2))))
     `(vertico-posframe-border-fallback ((t (:background ,level2))))

     ;; Consult
     `(consult-file ((t (:foreground ,fg))))
     `(consult-bookmark ((t (:foreground ,emphasis))))
     `(consult-buffer ((t (:foreground ,fg))))
     `(consult-line-number ((t (:foreground ,level3))))
     `(consult-separator ((t (:foreground ,level2))))
     `(consult-async-failed ((t (:foreground ,level5))))
     `(consult-async-finished ((t (:foreground ,emphasis))))
     `(consult-async-running ((t (:foreground ,level4))))
     `(consult-async-split ((t (:foreground ,level4))))
     `(consult-grep-context ((t (:foreground ,level3))))
     `(consult-highlight-match ,match)
     `(consult-highlight-mark ,bold)
     `(consult-key ,bold)
     `(consult-preview-line ((t (:background ,level0))))
     `(consult-preview-match ,match)
     `(consult-narrow-indicator ,bold)

     ;; Which-key
     `(which-key-key-face ((t (:foreground ,emphasis))))
     `(which-key-separator-face ((t (:foreground ,level2))))
     `(which-key-command-description-face ((t (:foreground ,fg))))
     `(which-key-group-description-face ((t (:foreground ,level4))))
     `(which-key-special-key-face ((t (:foreground ,level5))))
     `(which-key-highlighted-command-face ((t (:foreground ,emphasis))))

     ;; Treemacs
     `(treemacs-root-face ((t (:foreground ,fg  :height 1.1))))
     `(treemacs-directory-face ((t (:foreground ,fg))))
     `(treemacs-file-face ((t (:foreground ,fg))))
     `(treemacs-git-modified-face ((t (:foreground ,level4))))
     `(treemacs-git-added-face ((t (:foreground ,emphasis))))
     `(treemacs-git-conflict-face ((t (:foreground ,level5))))
     `(treemacs-git-untracked-face ((t (:foreground ,level3))))
     `(treemacs-git-ignored-face ((t (:foreground ,level2))))

     ;; Solaire Mode
     `(solaire-default-face ((t (:background ,level0))))
     `(solaire-hl-line-face ((t (:background ,level1))))
     `(solaire-mode-line-face ((t (:background ,fg :foreground ,level0))))
     `(solaire-mode-line-inactive-face ((t (:background ,level1 :foreground ,level4))))

     ;; Popup
     `(popup-face ((t (:background ,level0 :foreground ,fg))))
     `(popup-menu-selection-face ((t (:background ,level1 :foreground ,fg))))
     `(popup-tip-face ((t (:background ,level1 :foreground ,fg))))

     ;; Indent Guides
     `(highlight-indent-guides-odd-face ((t (:background ,level0))))
     `(highlight-indent-guides-even-face ((t (:background ,bg))))
     `(highlight-indentation-face ((t (:background ,level0))))

     ;; Avy
     `(avy-lead-face ((t (:background ,emphasis :foreground ,level0))))
     `(avy-lead-face-0 ((t (:background ,level4 :foreground ,level0))))
     `(avy-lead-face-1 ((t (:background ,level3 :foreground ,level0))))
     `(avy-lead-face-2 ((t (:background ,level4 :foreground ,level0))))
     `(avy-background-face ((t (:foreground ,level2))))

     ;; Ediff
     `(ediff-current-diff-A ((t (:background ,level1 :foreground ,level5))))
     `(ediff-current-diff-B ((t (:background ,level1 :foreground ,emphasis))))
     `(ediff-current-diff-C ((t (:background ,level1 :foreground ,level4))))
     `(ediff-fine-diff-A ((t (:background ,level2 :foreground ,level5))))
     `(ediff-fine-diff-B ((t (:background ,level2 :foreground ,emphasis))))
     `(ediff-fine-diff-C ((t (:background ,level2 :foreground ,level4))))

     ;; Markdown
     `(markdown-code-face ((t (:inherit default :background ,level0))))
     `(markdown-inline-code-face ((t (:inherit default :background ,level0))))
     `(markdown-pre-face ((t (:inherit default :background ,level0))))
     `(markdown-table-face ((t (:inherit default))))
     `(markdown-language-keyword-face ((t (:inherit default :foreground ,level3))))
     `(markdown-language-info-face ((t (:inherit default :foreground ,level4))))
     `(markdown-link-face ((t (:inherit default :foreground ,link-color :underline t))))
     `(markdown-missing-link-face ((t (:inherit default :foreground ,level5))))
     `(markdown-reference-face ((t (:inherit default :foreground ,level3))))
     `(markdown-footnote-marker-face ((t (:inherit default :foreground ,level3))))
     `(markdown-footnote-text-face ((t (:inherit default :foreground ,level3))))
     `(markdown-url-face ((t (:inherit default :foreground ,link-color))))
     `(markdown-plain-url-face ((t (:inherit default :foreground ,link-color))))
     `(markdown-link-title-face ((t (:inherit default :foreground ,level3))))
     `(markdown-line-break-face ((t (:inherit default :underline (:color ,emphasis :style line :position t)))))
     `(markdown-comment-face ((t (:inherit default :foreground ,level3))))
     `(markdown-math-face ((t (:inherit default :foreground ,level4))))
     `(markdown-metadata-key-face ((t (:inherit default :foreground ,level4))))
     `(markdown-metadata-value-face ((t (:inherit default :foreground ,level3))))
     `(markdown-gfm-checkbox-face ((t (:inherit default :foreground ,level4))))
     `(markdown-highlight-face ((t (:inherit default :background ,level1))))
     `(markdown-hr-face ((t (:inherit default :foreground ,level3))))
     `(markdown-html-tag-name-face ((t (:inherit default :foreground ,level4))))
     `(markdown-html-tag-delimiter-face ((t (:inherit default :foreground ,level3))))
     `(markdown-html-attr-name-face ((t (:inherit default :foreground ,level4))))
     `(markdown-html-attr-value-face ((t (:inherit default :foreground ,level3))))
     `(markdown-html-entity-face ((t (:inherit default :foreground ,level4))))
     `(markdown-highlighting-face ((t (:inherit default :background ,level4 :foreground ,level0))))

     ;; Additional Markdown faces (NEW)
     `(markdown-blockquote-face ,code-block)
     `(markdown-bold-face ,bold)
     `(markdown-header-delimiter-face ((t (:inherit default :foreground ,level3))))
     `(markdown-header-face ((t (:inherit default :foreground ,level6))))
     `(markdown-header-face-5 ((t (:inherit default :foreground ,level2))))
     `(markdown-header-face-6 ((t (:inherit default :foreground ,level1))))
     `(markdown-header-rule-face ((t (:inherit default :foreground ,level3))))
     `(markdown-italic-face ((t (:foreground ,emphasis))))
     `(markdown-list-face ((t (:inherit default :foreground ,level4))))
     `(markdown-markup-face ((t (:inherit default :foreground ,level3))))
     `(markdown-strike-through-face ((t (:inherit default :foreground ,level3))))

     ;; Corfu
     `(corfu--bar ((t (:background ,level2))))
     `(corfu--cbar ((t (:background ,level2))))
     `(corfu-annotations ((t (:foreground ,level3))))
     `(corfu-bar ((t (:background ,level2))))
     `(corfu-border ((t (:background ,level2))))
     `(corfu-current ,match)
     `(corfu-default ,default)
     `(corfu-deprecated ((t (:foreground ,level4))))
     `(corfu-popupinfo ((t (:background ,level0))))

     ;; CUA
     `(cua-global-mark ,bold)
     `(cua-rectangle ((t (:background ,level4))))
     `(cua-rectangle-noselect ((t (:background ,level2))))

     ;; Fixed pitch
     `(fixed-pitch ((t (:inherit default))))

     ;; Focus
     `(focus-focused ((t nil)))
     `(focus-unfocused ((t (:foreground ,level2))))
     
     ;; Feature Mode (Gherkin)
     `(feature-and-keyword-face ,bold)
     `(feature-background-keyword-face ,bold)
     `(feature-but-keyword-face ,bold)
     `(feature-examples-keyword-face ,bold)
     `(feature-feature-keyword-face ,bold)
     `(feature-given-keyword-face ,bold)
     `(feature-rule-keyword-face ,bold)
     `(feature-scenario-keyword-face ,bold)
     `(feature-scenarioOutline-keyword-face ,bold)
     `(feature-then-keyword-face ,bold)
     `(feature-when-keyword-face ,bold)

     ;; Compilation
     `(compilation-error ((t (:foreground ,level5))))
     `(compilation-warning ((t (:foreground ,level4))))
     `(compilation-info ((t (:foreground ,emphasis))))
     `(compilation-line-number ((t (:foreground ,level3))))
     `(compilation-column-number ((t (:foreground ,level3))))
     `(compilation-mode-line-exit ((t (:foreground ,emphasis))))
     `(compilation-mode-line-fail ((t (:foreground ,level5))))
     `(compilation-mode-line-run ((t (:foreground ,level4))))

     ;; Dape (debugger)
     `(dape-breakpoint-face ((t (:foreground ,level5))))
     `(dape-source-line-face ((t (:background ,level1))))
     `(dape-repl-error-face ((t (:foreground ,level5))))
     `(dape-exception-description-face ((t (:foreground ,level5))))
     `(dape-expression-face ,bold)
     `(dape-hits-face ,optional)
     `(dape-log-face ,optional)
     `(dape-inlay-hint-face ((t (:foreground ,level3))))
     `(dape-header-line-active-face ((t (:background ,level0 :foreground ,emphasis))))
     `(dape-header-line-inactive-face ((t (:background ,level0 :foreground ,level3))))

     ;; EJC (SQL)
     `(ejc-flx-highlight-face ,match)
     `(ejc-result-table-borders-face ((t (:foreground ,level2))))
     `(ejc-separator-face ((t (:foreground ,level2))))

     ;; Hydra
     `(hydra-face-red ((t (:foreground ,rainbow-red))))
     `(hydra-face-blue ((t (:foreground ,rainbow-blue))))
     `(hydra-face-pink ((t (:foreground ,rainbow-magenta))))
     `(hydra-face-teal ((t (:foreground ,rainbow-cyan))))
     `(hydra-face-amaranth ((t (:foreground ,rainbow-yellow))))

     ;; Evil Goggles
     `(evil-goggles-default-face ((t (:background ,level1))))
     `(evil-goggles-delete-face ((t (:background ,level1 :foreground ,rainbow-red))))
     `(evil-goggles-paste-face ((t (:background ,level1 :foreground ,rainbow-green))))
     `(evil-goggles-yank-face ((t (:background ,level1 :foreground ,rainbow-yellow))))
     `(evil-goggles-change-face ((t (:background ,level1 :foreground ,rainbow-orange))))

     ;; Evil Snipe
     `(evil-snipe-first-match-face ,match)
     `(evil-snipe-matches-face ,replace-match*)

     ;; Eldoc
     `(eldoc-highlight-function-argument ,bold)
     `(eldoc-box-body ((t (:background ,level0 :foreground ,fg))))
     `(eldoc-box-border ((t (:background ,level2))))

     ;; hl-todo
     `(hl-todo ((t (:foreground ,emphasis :weight normal))))

     ;; GPTel
     `(gptel-response-highlight ((t (:background ,level0))))))

  (defvar company-format-margin-function)
  (setq company-format-margin-function nil))

(provide 'nibelung-theme-base)
;;; nibelung-theme-base.el ends here
