;;; pierre-themes.el --- Pierre themes for Emacs -*- lexical-binding: t; -*-

;; Author: Shane Kennedy
;; Version: 1.0.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: faces, themes
;; URL: https://github.com/pierre-coding/theme

;;; Commentary:

;; Emacs recreations of the official @pierre/theme Pierre Dark and Pierre
;; Light themes.  The palettes and syntax colors are taken from @pierre/theme
;; 1.1.0 (themes/pierre-dark.json and themes/pierre-light.json).

;;; Code:

;;;###autoload
(let ((dir (file-name-directory (or load-file-name buffer-file-name))))
  (when dir
    (add-to-list 'custom-theme-load-path dir)))

(defgroup pierre-themes nil
  "Pierre themes."
  :group 'faces)

(defconst pierre-themes--themes '(pierre-dark pierre-light)
  "Themes provided by pierre-themes.")

(defun pierre-themes--disable-other-themes (theme &rest _args)
  "When enabling THEME, disable the other Pierre theme.
This prevents stale background/foreground faces when switching directly
between `pierre-dark' and `pierre-light'."
  (when (memq theme pierre-themes--themes)
    (dolist (other pierre-themes--themes)
      (when (and (not (eq other theme))
                 (custom-theme-enabled-p other))
        (disable-theme other)))))

(advice-add 'enable-theme :after #'pierre-themes--disable-other-themes)

(defun pierre-themes--color (palette name)
  "Return from PALETTE the color named NAME."
  (alist-get name palette))

(defun pierre-themes--apply (theme palette dark-p)
  "Apply PALETTE to THEME.
DARK-P is non-nil for the dark variant."
  (let* ((class '((class color) (min-colors 89)))
         (c (lambda (name) (pierre-themes--color palette name)))
         (bg (funcall c 'bg))
         (fg (funcall c 'fg))
         (bg-alt (funcall c 'bg-alt))
         (bg-panel (funcall c 'bg-panel))
         (bg-input (funcall c 'bg-input))
         (border (funcall c 'border))
         (selection (funcall c 'selection))
         (selection-soft (funcall c 'selection-soft))
         (hl-line (funcall c 'hl-line))
         (cursor (funcall c 'cursor))
         (line-number (funcall c 'line-number))
         (line-number-active (funcall c 'line-number-active))
         (comment (funcall c 'comment))
         (muted (funcall c 'muted))
         (punctuation (funcall c 'punctuation))
         (string (funcall c 'string))
         (number (funcall c 'number))
         (constant (funcall c 'constant))
         (variable-constant (funcall c 'variable-constant))
         (keyword (funcall c 'keyword))
         (variable (funcall c 'variable))
         (parameter (funcall c 'parameter))
         (function (funcall c 'function))
         (type (funcall c 'type))
         (namespace (funcall c 'namespace))
         (operator (funcall c 'operator))
         (decorator (funcall c 'decorator))
         (regexp (funcall c 'regexp))
         (regex-alt (funcall c 'regex-alt))
         (tag (funcall c 'tag))
         (red (funcall c 'red))
         (green (funcall c 'green))
         (yellow (funcall c 'yellow))
         (blue (funcall c 'blue))
         (magenta (funcall c 'magenta))
         (cyan (funcall c 'cyan))
         (white (funcall c 'white))
         (black (funcall c 'black))
         (diff-add-bg (funcall c 'diff-add-bg))
         (diff-del-bg (funcall c 'diff-del-bg))
         (merge-current-bg (funcall c 'merge-current-bg))
         (merge-incoming-bg (funcall c 'merge-incoming-bg)))
    (custom-theme-set-faces
     theme
     `(default ((,class (:background ,bg :foreground ,fg))))
     `(cursor ((,class (:background ,cursor))))
     `(fringe ((,class (:background ,bg :foreground ,line-number))))
     `(region ((,class (:background ,selection))))
     `(secondary-selection ((,class (:background ,selection-soft))))
     `(highlight ((,class (:background ,selection-soft))))
     `(hl-line ((,class (:background ,hl-line))))
     `(line-number ((,class (:foreground ,line-number :background ,bg))))
     `(line-number-current-line ((,class (:foreground ,line-number-active :background ,bg))))
     `(vertical-border ((,class (:foreground ,border))))
     `(window-divider ((,class (:foreground ,border))))
     `(window-divider-first-pixel ((,class (:foreground ,border))))
     `(window-divider-last-pixel ((,class (:foreground ,border))))
     `(minibuffer-prompt ((,class (:foreground ,blue :weight bold))))
     `(escape-glyph ((,class (:foreground ,yellow))))
     `(homoglyph ((,class (:foreground ,yellow))))
     `(link ((,class (:foreground ,blue :underline t))))
     `(link-visited ((,class (:foreground ,magenta :underline t))))
     `(button ((,class (:foreground ,blue :underline t))))
     `(shadow ((,class (:foreground ,muted))))
     `(success ((,class (:foreground ,green))))
     `(warning ((,class (:foreground ,yellow))))
     `(error ((,class (:foreground ,red))))
     `(match ((,class (:background ,(if dark-p "#613f00" "#fff0b3") :foreground ,fg))))
     `(lazy-highlight ((,class (:background ,(if dark-p "#19283c" "#dfebff") :foreground ,fg))))
     `(isearch ((,class (:background ,yellow :foreground ,black :weight bold))))
     `(isearch-fail ((,class (:background ,red :foreground ,(if dark-p black white)))))
     `(trailing-whitespace ((,class (:background ,red))))
     `(show-paren-match ((,class (:background ,selection :foreground ,fg :weight bold))))
     `(show-paren-mismatch ((,class (:background ,red :foreground ,(if dark-p black white)))))
     `(header-line ((,class (:background ,bg-panel :foreground ,fg :box (:line-width -1 :color ,border)))))
     `(mode-line ((,class (:background ,bg-panel :foreground ,fg :box (:line-width -1 :color ,border)))))
     `(mode-line-inactive ((,class (:background ,bg-alt :foreground ,line-number :box (:line-width -1 :color ,border)))))
     `(mode-line-highlight ((,class (:foreground ,blue :box nil))))
     `(tab-bar ((,class (:background ,bg-panel :foreground ,muted))))
     `(tab-bar-tab ((,class (:background ,bg :foreground ,fg :box (:line-width -1 :color ,blue)))))
     `(tab-bar-tab-inactive ((,class (:background ,bg-panel :foreground ,line-number))))
     `(tab-line ((,class (:background ,bg-panel :foreground ,muted))))
     `(tab-line-tab ((,class (:background ,bg :foreground ,fg :box (:line-width -1 :color ,blue)))))
     `(tab-line-tab-inactive ((,class (:background ,bg-panel :foreground ,line-number))))

     ;; Font Lock, mirroring Pierre's TextMate/semantic token colors.
     `(font-lock-builtin-face ((,class (:foreground ,namespace))))
     `(font-lock-comment-face ((,class (:foreground ,comment))))
     `(font-lock-comment-delimiter-face ((,class (:foreground ,comment))))
     `(font-lock-constant-face ((,class (:foreground ,constant))))
     `(font-lock-doc-face ((,class (:foreground ,string))))
     `(font-lock-doc-markup-face ((,class (:foreground ,tag))))
     `(font-lock-function-call-face ((,class (:foreground ,function))))
     `(font-lock-function-name-face ((,class (:foreground ,function))))
     `(font-lock-keyword-face ((,class (:foreground ,keyword))))
     `(font-lock-negation-char-face ((,class (:foreground ,operator))))
     `(font-lock-number-face ((,class (:foreground ,number))))
     `(font-lock-operator-face ((,class (:foreground ,operator))))
     `(font-lock-preprocessor-face ((,class (:foreground ,decorator))))
     `(font-lock-property-name-face ((,class (:foreground ,variable))))
     `(font-lock-property-use-face ((,class (:foreground ,variable))))
     `(font-lock-punctuation-face ((,class (:foreground ,punctuation))))
     `(font-lock-regexp-grouping-backslash ((,class (:foreground ,regexp))))
     `(font-lock-regexp-grouping-construct ((,class (:foreground ,regex-alt))))
     `(font-lock-string-face ((,class (:foreground ,string))))
     `(font-lock-type-face ((,class (:foreground ,type))))
     `(font-lock-variable-name-face ((,class (:foreground ,variable))))
     `(font-lock-variable-use-face ((,class (:foreground ,variable))))
     `(font-lock-warning-face ((,class (:foreground ,yellow :weight bold))))

     ;; Tree-sitter and common semantic faces.
     `(tree-sitter-hl-face:attribute ((,class (:foreground ,decorator))))
     `(tree-sitter-hl-face:comment ((,class (:foreground ,comment))))
     `(tree-sitter-hl-face:constant ((,class (:foreground ,constant))))
     `(tree-sitter-hl-face:constant.builtin ((,class (:foreground ,namespace))))
     `(tree-sitter-hl-face:constructor ((,class (:foreground ,type))))
     `(tree-sitter-hl-face:embedded ((,class (:foreground ,fg))))
     `(tree-sitter-hl-face:function ((,class (:foreground ,function))))
     `(tree-sitter-hl-face:function.builtin ((,class (:foreground ,function))))
     `(tree-sitter-hl-face:function.call ((,class (:foreground ,function))))
     `(tree-sitter-hl-face:keyword ((,class (:foreground ,keyword))))
     `(tree-sitter-hl-face:method ((,class (:foreground ,function))))
     `(tree-sitter-hl-face:method.call ((,class (:foreground ,function))))
     `(tree-sitter-hl-face:number ((,class (:foreground ,number))))
     `(tree-sitter-hl-face:operator ((,class (:foreground ,operator))))
     `(tree-sitter-hl-face:property ((,class (:foreground ,variable))))
     `(tree-sitter-hl-face:punctuation ((,class (:foreground ,punctuation))))
     `(tree-sitter-hl-face:string ((,class (:foreground ,string))))
     `(tree-sitter-hl-face:string.special ((,class (:foreground ,regexp))))
     `(tree-sitter-hl-face:tag ((,class (:foreground ,tag))))
     `(tree-sitter-hl-face:type ((,class (:foreground ,type))))
     `(tree-sitter-hl-face:type.builtin ((,class (:foreground ,type))))
     `(tree-sitter-hl-face:variable ((,class (:foreground ,variable))))
     `(tree-sitter-hl-face:variable.parameter ((,class (:foreground ,parameter))))

     ;; Language/package specific syntax faces.
     `(js2-function-param ((,class (:foreground ,parameter))))
     `(js2-object-property ((,class (:foreground ,variable))))
     `(js2-object-property-access ((,class (:foreground ,variable))))
     `(js2-external-variable ((,class (:foreground ,namespace))))
     `(js2-jsdoc-tag ((,class (:foreground ,decorator))))
     `(js2-jsdoc-type ((,class (:foreground ,type))))
     `(typescript-jsdoc-tag ((,class (:foreground ,decorator))))
     `(typescript-jsdoc-type ((,class (:foreground ,type))))
     `(web-mode-html-tag-face ((,class (:foreground ,tag))))
     `(web-mode-html-tag-bracket-face ((,class (:foreground ,punctuation))))
     `(web-mode-html-attr-name-face ((,class (:foreground ,variable))))
     `(web-mode-html-attr-value-face ((,class (:foreground ,string))))
     `(web-mode-css-property-name-face ((,class (:foreground ,variable))))
     `(web-mode-css-selector-face ((,class (:foreground ,tag))))
     `(css-selector ((,class (:foreground ,tag))))
     `(css-property ((,class (:foreground ,variable))))
     `(markdown-header-face ((,class (:foreground ,function :weight bold))))
     `(markdown-header-delimiter-face ((,class (:foreground ,punctuation))))
     `(markdown-code-face ((,class (:background ,bg-input :foreground ,fg))))
     `(markdown-inline-code-face ((,class (:background ,bg-input :foreground ,string))))
     `(markdown-link-face ((,class (:foreground ,blue :underline t))))
     `(markdown-url-face ((,class (:foreground ,string))))

     ;; UI/completion/search.
     `(completions-common-part ((,class (:foreground ,blue))))
     `(completions-first-difference ((,class (:foreground ,keyword :weight bold))))
     `(completion-preview ((,class (:foreground ,muted))))
     `(company-tooltip ((,class (:background ,bg-panel :foreground ,fg))))
     `(company-tooltip-selection ((,class (:background ,selection :foreground ,fg))))
     `(company-tooltip-common ((,class (:foreground ,blue :weight bold))))
     `(company-tooltip-annotation ((,class (:foreground ,muted))))
     `(company-scrollbar-bg ((,class (:background ,bg-input))))
     `(company-scrollbar-fg ((,class (:background ,line-number))))
     `(company-preview ((,class (:background ,selection :foreground ,fg))))
     `(corfu-default ((,class (:background ,bg-panel :foreground ,fg))))
     `(corfu-current ((,class (:background ,selection :foreground ,fg))))
     `(corfu-annotations ((,class (:foreground ,muted))))
     `(vertico-current ((,class (:background ,selection :foreground ,fg))))
     `(orderless-match-face-0 ((,class (:foreground ,blue :weight bold))))
     `(orderless-match-face-1 ((,class (:foreground ,magenta :weight bold))))
     `(orderless-match-face-2 ((,class (:foreground ,green :weight bold))))
     `(orderless-match-face-3 ((,class (:foreground ,yellow :weight bold))))
     `(consult-highlight-match ((,class (:foreground ,blue :weight bold))))
     `(consult-preview-match ((,class (:background ,selection :foreground ,fg))))
     `(ivy-current-match ((,class (:background ,selection :foreground ,fg))))
     `(ivy-minibuffer-match-face-1 ((,class (:foreground ,blue))))
     `(ivy-minibuffer-match-face-2 ((,class (:foreground ,magenta :weight bold))))
     `(ivy-minibuffer-match-face-3 ((,class (:foreground ,green :weight bold))))
     `(ivy-minibuffer-match-face-4 ((,class (:foreground ,yellow :weight bold))))
     `(helm-selection ((,class (:background ,selection :foreground ,fg))))
     `(helm-match ((,class (:foreground ,blue :weight bold))))
     `(which-key-key-face ((,class (:foreground ,blue :weight bold))))
     `(which-key-command-description-face ((,class (:foreground ,fg))))
     `(which-key-group-description-face ((,class (:foreground ,magenta))))
     `(which-key-separator-face ((,class (:foreground ,punctuation))))

     ;; Dired, compilation, diagnostics.
     `(dired-directory ((,class (:foreground ,blue :weight bold))))
     `(dired-symlink ((,class (:foreground ,cyan))))
     `(dired-ignored ((,class (:foreground ,muted))))
     `(compilation-info ((,class (:foreground ,green))))
     `(compilation-warning ((,class (:foreground ,yellow))))
     `(compilation-error ((,class (:foreground ,red))))
     `(flyspell-incorrect ((,class (:underline (:style wave :color ,red)))))
     `(flyspell-duplicate ((,class (:underline (:style wave :color ,yellow)))))
     `(flymake-error ((,class (:underline (:style wave :color ,red)))))
     `(flymake-warning ((,class (:underline (:style wave :color ,yellow)))))
     `(flymake-note ((,class (:underline (:style wave :color ,blue)))))
     `(flycheck-error ((,class (:underline (:style wave :color ,red)))))
     `(flycheck-warning ((,class (:underline (:style wave :color ,yellow)))))
     `(flycheck-info ((,class (:underline (:style wave :color ,blue)))))
     `(eglot-diagnostic-tag-unnecessary-face ((,class (:foreground ,muted))))
     `(eglot-highlight-symbol-face ((,class (:background ,selection-soft))))
     `(lsp-face-highlight-textual ((,class (:background ,selection-soft))))
     `(lsp-face-highlight-read ((,class (:background ,selection-soft))))
     `(lsp-face-highlight-write ((,class (:background ,selection))))

     ;; Diff, ediff, smerge, vc and magit.
     `(diff-added ((,class (:background ,diff-add-bg :foreground ,green))))
     `(diff-removed ((,class (:background ,diff-del-bg :foreground ,red))))
     `(diff-changed ((,class (:background ,selection-soft :foreground ,yellow))))
     `(diff-refine-added ((,class (:background ,green :foreground ,(if dark-p black white)))))
     `(diff-refine-removed ((,class (:background ,red :foreground ,(if dark-p black white)))))
     `(diff-header ((,class (:background ,bg-panel :foreground ,muted))))
     `(diff-file-header ((,class (:background ,bg-panel :foreground ,fg :weight bold))))
     `(diff-hunk-header ((,class (:background ,selection-soft :foreground ,blue))))
     `(diff-context ((,class (:foreground ,fg))))
     `(ediff-current-diff-A ((,class (:background ,diff-del-bg))))
     `(ediff-current-diff-B ((,class (:background ,diff-add-bg))))
     `(ediff-current-diff-C ((,class (:background ,merge-current-bg))))
     `(ediff-fine-diff-A ((,class (:background ,red :foreground ,(if dark-p black white)))))
     `(ediff-fine-diff-B ((,class (:background ,green :foreground ,(if dark-p black white)))))
     `(ediff-even-diff-A ((,class (:background ,bg-panel))))
     `(ediff-even-diff-B ((,class (:background ,bg-panel))))
     `(ediff-odd-diff-A ((,class (:background ,bg-alt))))
     `(ediff-odd-diff-B ((,class (:background ,bg-alt))))
     `(smerge-base ((,class (:background ,merge-current-bg))))
     `(smerge-mine ((,class (:background ,diff-del-bg))))
     `(smerge-other ((,class (:background ,merge-incoming-bg))))
     `(smerge-markers ((,class (:background ,bg-panel :foreground ,muted))))
     `(smerge-refined-added ((,class (:background ,green :foreground ,(if dark-p black white)))))
     `(smerge-refined-removed ((,class (:background ,red :foreground ,(if dark-p black white)))))
     `(vc-edited-state ((,class (:foreground ,blue))))
     `(vc-added-state ((,class (:foreground ,green))))
     `(vc-removed-state ((,class (:foreground ,red))))
     `(vc-conflict-state ((,class (:foreground ,magenta))))
     `(magit-section-heading ((,class (:foreground ,blue :weight bold))))
     `(magit-section-highlight ((,class (:background ,hl-line))))
     `(magit-branch-local ((,class (:foreground ,blue))))
     `(magit-branch-remote ((,class (:foreground ,green))))
     `(magit-hash ((,class (:foreground ,muted))))
     `(magit-diff-context ((,class (:foreground ,fg))))
     `(magit-diff-context-highlight ((,class (:background ,hl-line :foreground ,fg))))
     `(magit-diff-added ((,class (:background ,diff-add-bg :foreground ,green))))
     `(magit-diff-added-highlight ((,class (:background ,diff-add-bg :foreground ,green :weight bold))))
     `(magit-diff-removed ((,class (:background ,diff-del-bg :foreground ,red))))
     `(magit-diff-removed-highlight ((,class (:background ,diff-del-bg :foreground ,red :weight bold))))
     `(magit-diff-file-heading ((,class (:foreground ,fg :weight bold))))
     `(magit-diff-file-heading-highlight ((,class (:background ,hl-line :foreground ,fg :weight bold))))
     `(magit-diff-hunk-heading ((,class (:background ,selection-soft :foreground ,blue))))
     `(magit-diff-hunk-heading-highlight ((,class (:background ,selection :foreground ,fg))))
     `(magit-diffstat-added ((,class (:foreground ,green))))
     `(magit-diffstat-removed ((,class (:foreground ,red))))
     `(magit-process-ok ((,class (:foreground ,green))))
     `(magit-process-ng ((,class (:foreground ,red))))

     ;; Org.
     `(org-level-1 ((,class (:foreground ,function :weight bold :height 1.20))))
     `(org-level-2 ((,class (:foreground ,type :weight bold :height 1.12))))
     `(org-level-3 ((,class (:foreground ,keyword :weight bold :height 1.06))))
     `(org-level-4 ((,class (:foreground ,variable-constant :weight bold))))
     `(org-level-5 ((,class (:foreground ,string :weight bold))))
     `(org-level-6 ((,class (:foreground ,cyan :weight bold))))
     `(org-level-7 ((,class (:foreground ,magenta :weight bold))))
     `(org-level-8 ((,class (:foreground ,yellow :weight bold))))
     `(org-block ((,class (:background ,bg-input :foreground ,fg))))
     `(org-block-begin-line ((,class (:background ,bg-panel :foreground ,muted))))
     `(org-block-end-line ((,class (:background ,bg-panel :foreground ,muted))))
     `(org-code ((,class (:foreground ,string))))
     `(org-verbatim ((,class (:foreground ,string))))
     `(org-link ((,class (:foreground ,blue :underline t))))
     `(org-date ((,class (:foreground ,cyan))))
     `(org-todo ((,class (:foreground ,red :weight bold))))
     `(org-done ((,class (:foreground ,green :weight bold))))
     `(org-warning ((,class (:foreground ,yellow :weight bold))))
     `(org-table ((,class (:foreground ,cyan))))
     `(org-document-title ((,class (:foreground ,fg :weight bold :height 1.25))))
     `(org-document-info ((,class (:foreground ,muted))))

     ;; Terminals and ANSI.
     `(ansi-color-black ((,class (:foreground ,black :background ,black))))
     `(ansi-color-red ((,class (:foreground ,red :background ,red))))
     `(ansi-color-green ((,class (:foreground ,green :background ,green))))
     `(ansi-color-yellow ((,class (:foreground ,yellow :background ,yellow))))
     `(ansi-color-blue ((,class (:foreground ,blue :background ,blue))))
     `(ansi-color-magenta ((,class (:foreground ,magenta :background ,magenta))))
     `(ansi-color-cyan ((,class (:foreground ,cyan :background ,cyan))))
     `(ansi-color-white ((,class (:foreground ,white :background ,white))))
     `(term-color-black ((,class (:foreground ,black :background ,black))))
     `(term-color-red ((,class (:foreground ,red :background ,red))))
     `(term-color-green ((,class (:foreground ,green :background ,green))))
     `(term-color-yellow ((,class (:foreground ,yellow :background ,yellow))))
     `(term-color-blue ((,class (:foreground ,blue :background ,blue))))
     `(term-color-magenta ((,class (:foreground ,magenta :background ,magenta))))
     `(term-color-cyan ((,class (:foreground ,cyan :background ,cyan))))
     `(term-color-white ((,class (:foreground ,white :background ,white))))
     `(eshell-prompt ((,class (:foreground ,blue :weight bold))))
     `(eshell-ls-directory ((,class (:foreground ,blue :weight bold))))
     `(eshell-ls-symlink ((,class (:foreground ,cyan))))
     `(eshell-ls-executable ((,class (:foreground ,green))))
     `(eshell-ls-missing ((,class (:foreground ,red))))
     `(eshell-ls-readonly ((,class (:foreground ,yellow))))
     `(eshell-ls-unreadable ((,class (:foreground ,muted))))

     ;; Misc.
     `(help-key-binding ((,class (:background ,bg-input :foreground ,blue :box (:line-width -1 :color ,border)))))
     `(widget-field ((,class (:background ,bg-input :foreground ,fg :box (:line-width -1 :color ,border)))))
     `(custom-button ((,class (:background ,blue :foreground ,(if dark-p black white) :box nil))))
     `(custom-button-mouse ((,class (:background ,(if dark-p "#0190e7" "#1aa9ff") :foreground ,(if dark-p black white) :box nil))))
     `(custom-variable-tag ((,class (:foreground ,blue :weight bold))))
     `(custom-group-tag ((,class (:foreground ,function :weight bold :height 1.2))))
     `(rainbow-delimiters-depth-1-face ((,class (:foreground ,punctuation))))
     `(rainbow-delimiters-depth-2-face ((,class (:foreground ,blue))))
     `(rainbow-delimiters-depth-3-face ((,class (:foreground ,magenta))))
     `(rainbow-delimiters-depth-4-face ((,class (:foreground ,green))))
     `(rainbow-delimiters-depth-5-face ((,class (:foreground ,yellow))))
     `(rainbow-delimiters-depth-6-face ((,class (:foreground ,keyword))))
     `(rainbow-delimiters-depth-7-face ((,class (:foreground ,cyan))))
     `(rainbow-delimiters-depth-8-face ((,class (:foreground ,type))))
     `(rainbow-delimiters-depth-9-face ((,class (:foreground ,variable))))
     `(rainbow-delimiters-unmatched-face ((,class (:foreground ,red :weight bold))))
     `(whitespace-space ((,class (:foreground ,border))))
     `(whitespace-tab ((,class (:foreground ,border))))
     `(whitespace-newline ((,class (:foreground ,border))))
     `(whitespace-trailing ((,class (:background ,red))))
     `(eldoc-highlight-function-argument ((,class (:foreground ,parameter :weight bold))))
     `(pulse-highlight-start-face ((,class (:background ,selection))))
     `(pulse-highlight-face ((,class (:background ,selection)))))
    (let ((ansi-color-vector (vector black red green yellow blue magenta cyan white))
        (ansi-term-vector (vector 'unspecified black red green yellow blue magenta cyan white)))
    (custom-theme-set-variables
     theme
     `(ansi-color-names-vector ',ansi-color-vector)
     `(ansi-term-color-vector ',ansi-term-vector)))))

(defconst pierre-themes--dark-palette
  '((bg . "#0a0a0a")
    (fg . "#fafafa")
    (bg-alt . "#101010")
    (bg-panel . "#171717")
    (bg-input . "#1d1d1d")
    (border . "#1d1d1d")
    (selection . "#19283c")
    (selection-soft . "#102234")
    (hl-line . "#19283c")
    (cursor . "#009fff")
    (line-number . "#737373")
    (line-number-active . "#a3a3a3")
    (comment . "#737373")
    (muted . "#a3a3a3")
    (punctuation . "#636363")
    (string . "#5ecc71")
    (number . "#68cdf2")
    (constant . "#ffd452")
    (variable-constant . "#ffab16")
    (keyword . "#ff678d")
    (variable . "#ffa359")
    (parameter . "#a3a3a3")
    (function . "#9d6afb")
    (type . "#d568ea")
    (namespace . "#ffab16")
    (operator . "#08c0ef")
    (decorator . "#69b1ff")
    (regexp . "#64d1db")
    (regex-alt . "#61d5c0")
    (tag . "#ff855e")
    (red . "#ff2e3f")
    (green . "#07c480")
    (yellow . "#ffca00")
    (blue . "#009fff")
    (magenta . "#e130ac")
    (cyan . "#08c0ef")
    (white . "#bcbcbc")
    (black . "#171717")
    (diff-add-bg . "#0b1d17")
    (diff-del-bg . "#210e10")
    (merge-current-bg . "#301f53")
    (merge-incoming-bg . "#0c3540"))
  "Pierre Dark palette from @pierre/theme 1.1.0.")

(defconst pierre-themes--light-palette
  '((bg . "#ffffff")
    (fg . "#0a0a0a")
    (bg-alt . "#f7f7f7")
    (bg-panel . "#f5f5f5")
    (bg-input . "#ededed")
    (border . "#e5e5e5")
    (selection . "#dfebff")
    (selection-soft . "#edf5ff")
    (hl-line . "#dfebff")
    (cursor . "#009fff")
    (line-number . "#737373")
    (line-number-active . "#525252")
    (comment . "#737373")
    (muted . "#525252")
    (punctuation . "#636363")
    (string . "#199f43")
    (number . "#1ca1c7")
    (constant . "#d5a910")
    (variable-constant . "#d5901c")
    (keyword . "#d32a61")
    (variable . "#d47628")
    (parameter . "#636363")
    (function . "#693acf")
    (type . "#a631be")
    (namespace . "#d5901c")
    (operator . "#08c0ef")
    (decorator . "#1a85d4")
    (regexp . "#17a5af")
    (regex-alt . "#16a994")
    (tag . "#d5512f")
    (red . "#d52c36")
    (green . "#18a46c")
    (yellow . "#d5a910")
    (blue . "#009fff")
    (magenta . "#bd2e90")
    (cyan . "#1ca1c7")
    (white . "#bcbcbc")
    (black . "#1d1d1d")
    (diff-add-bg . "#d1ede2")
    (diff-del-bg . "#f7d5d7")
    (merge-current-bg . "#e1d8f7")
    (merge-incoming-bg . "#d2ecf3"))
  "Pierre Light palette from @pierre/theme 1.1.0.")

(provide 'pierre-themes)

;;; pierre-themes.el ends here
